### ISSUE TITLE
Leverage Github Releases

### ISSUE THREAD

**Issue by kenperkins** [pkgcloud/pkgcloud#240]
https://github.com/blog/1547-release-your-software

**Comment by everett-toews** [comment]
Any movement here?

https://github.com/pkgcloud/pkgcloud/releases.atom does work so we can just go with that.

**Comment by rosskukulinski** [comment]
@everett-toews I think we _are_ using GitHub releases: https://github.com/pkgcloud/pkgcloud/releases

**Comment by everett-toews** [comment]
Ya. Looks like it to me but I didn't see much in the way of descriptions there so I wasn't sure.

**Comment by rosskukulinski** [comment]
yep, marking as closed -- @kenperkins has been doing this for a while.  Issue must have gotten lost in the noise.  Thanks @everett-toews

**Comment by kenperkins** [comment]
So part of our release process is using npm to bump `package.json` version numbers, which also auto tags the commit. I'll have to look and see if this allows us to offer more information.
