### ISSUE TITLE
Should a 404 on a container raise an error?

### ISSUE THREAD

**Issue by kenperkins** [pkgcloud/pkgcloud#270]
Currently, pkgcloud will return an error when you call getContainer on the rackspace/openstack storage provider if the container doesn't exist.

``` javascript
var client =  pkgcloud.providers.rackspace.storage.createClient(config.getConfig());

client.getContainer('this-wont-exist', function (err, container) {
  if (err) {
    log.error(err);
    return;
  }

  // we'll never get here
  log.info(container.toJSON());
});
```

I'm not convinced this is the right design. A missing entity is not an error case, it's just not found.

Curious what other folks think...

**Comment by JeffGreat** [comment]
Then, API should provide a hasContainer method to avoid rising useless exception, or at list, provide filters on getContainers. As @rosskukulinski wrote, there are many situations where one need that kind of operation to waterfall or whatever.
