### ISSUE TITLE
Unable to authenticate due to pkgcloud changing the authUrl

### ISSUE THREAD

**Issue by Webbpiraten** [pkgcloud/pkgcloud#336]
**pkgcloud version: 0.9.6**
**node version: 0.10.32**
**npm version: 1.4.28**

I'm trying to create a client:

``` javascript
var Compute = {
    provider: 'openstack',
    username: 'myName',
    password: 'myPass',
    authUrl: '-IpAddr-:5000/v2.0/tokens'
};
var client = pkgcloud.compute.createClient(Compute);
```

This will fail with the response:

``` javascript
{ [Error: Error (404): Item not found]
  name: 'Error',
  failCode: 'Item not found',
  statusCode: 404,
  href: '-ip-:5000/v2.0/tokens/v2.0/tokens',
  method: 'POST',
  headers:
   { vary: 'X-Auth-Token',
     'x-distribution': 'Ubuntu',
     'content-type': 'application/json',
     'content-length': '93',
     date: 'Derp',
     connection: 'keep-alive' },
  result:
   { error:
      { message: 'The resource could not be found.',
        code: 404,
        title: 'Not Found' } } }
```

The problem is that when I use 

``` javascript
authUrl: '-IpAddr-:5000/v2.0/tokens'
```

pkgcloud changes the URL to 

``` javascript
'-IpAddr-:5000/v2.0/tokens/v2.0/tokens'
```

But when I only use

``` javascript
'-IpAddr-:5000/'
```

I get 

``` javascript
[Error: Unable to identify endpoint url]
```

Any solutions?

**Comment by paul42** [comment]
So, not certain if I should open this issue back up or start a new one, but I'm also working on an enterprise install and having the same issue:
var pkgcloud = require('pkgcloud');
var compute = {
  provider: 'openstack',
  username: 'paul42',
  password: process.env.OS_PASSWORD,
  authUrl: 'https://openstack.internal.company.com:5000',
  basePath: 'v2.0'
}

var client = pkgcloud.compute.createClient(compute);

client.getFlavors(function (err, flavors) {
    if (err) {
        console.dir(err);
        return;
    }
    console.log(flavors);
  });

This returns:

{ [Error: Error (400): Bad Request]
  name: 'Error',
  failCode: 'Bad Request',
  statusCode: 400,
  href: 'https://openstack.internal.company.com:5000/v2.0',
  method: 'POST',
  headers:
   { vary: 'X-Auth-Token',
     'content-type': 'application/json',
     'content-length': '121',
     date: 'Mon, 06 Apr 2015 22:30:13 GMT',
     connection: 'close' },
  result:
   { error:
      { message: 'get_version_v2() got an unexpected keyword argument \'auth\'',
        code: 400,
        title: 'Bad Request' } } }

what can I tell the internal openstack team to check to fix this?

when I don't use 'basePath' at all I get:
[Error: Unable to identify endpoint url]

Thanks in advance,
Paul

**Comment by mmdonohue** [comment]
One thing I found is if you don't specify the region you can have a case where no endpoint is returned and hence [Error: Unable to identify endpoint url].
I modified my local openstack/context/service.js to this to correct.

  if (options.region) {
    _.each(self.endpoints, function (endpoint) {
      if (!endpoint.region || !matchRegion(endpoint.region, options.region)) {
        return;
      }

      url = getUrl(endpoint);
    });
  }
  else {
    _.each(self.endpoints, function(endpoint) {

	   url = getUrl(endpoint); // <- added
      if (url) {
        return;
      }

      // return the first region-less endpoint
      if (!endpoint.region) {
        url = getUrl(endpoint); // <- There can be no endpoints that don't have a region!
      }
    });
  }

**Comment by kenperkins** [comment]
@mmdonohue your code sample seems a bit off, can you clean it up so I can understand what you're articulating?

**Comment by mmdonohue** [comment]
Sorry, I wasn't suggesting a code change. Just noting that if you don't specify a region as an OpenStack connection option you can get the  [Error: Unable to identify endpoint url].
The part below- **// return the first region-less endpoint**
Can in some cases not find any region-less endpoints.

**Comment by anselanza** [comment]
Aaaaah the region helped so much, thank you! I was using Rackspace Cloud Files and if I didn't specify "region": "IAD" (or whatever) then I would get `[Error: Unable to identify endpoint url]`
