### ISSUE TITLE
Is there support for openstack v3 identity (keystone) ?

### ISSUE THREAD

**Issue by amortiz** [pkgcloud/pkgcloud#367]
I've played around with your code a bit, and i'm wondering if you have support for authenticating against a v3 only version of Keystone. A payload structure for /auth/tokens is something like this:

{
    "auth": {
        "identity": {
            "methods": [
                "password"
            ],
            "password": {
                "user": {
                    "id": "0ca8f6",
                    "password": "secretsecret"
                }
            }
        },
        "scope": {
            "project": {
                "domain": {
                    "id": "1789d1"
                },
                "name": "project-x"
            }
        }
    }
}

Is there something that allows you to send something like that? I see that there's an overridable "identity" object, so was wondering if there was something that was working against v3 first.

**Comment by BobDickinson** [comment]
See this issue:

https://github.com/pkgcloud/pkgcloud/issues/477

OpenStack v3 identity is now supported.

This should be closed.
