### ISSUE TITLE
Temp URL feature for Cloud Storage

### ISSUE THREAD

**Issue by mikevalstar** [pkgcloud/pkgcloud#376]
Feature request:

I'd like to request support for Temp URLs be added to pkgcloud. (specifically for Rackspace, but I do know Amazon S3 also supports this feature)

Documentation on feature: http://docs.rackspace.com/files/api/v1/cf-devguide/content/TempURL-d1a4450.html

I assume a call for the container would need to be added to attach the Temp URL key, and another call on the files class to generate a Temp URL.

example for Amazon S3: http://stackoverflow.com/questions/10044151/how-to-generate-a-temporary-url-to-upload-file-to-amazon-s3-with-boto-library

**Comment by jonaswindey** [comment]
+1 for this one

**Comment by hboylan** [comment]
+1 would be helpful

**Comment by dantman** [comment]
+1 I'll probably need this for AWS.

**Comment by hboylan** [comment]
This snippet successfully generates a URL, but it returns ```401 Unauthorized: Temp URL invalid```

```javascript
var pkgcloud = require('pkgcloud')
var rackspace = pkgcloud.storage.createClient({
  provider: 'rackspace', // required
  username: '{username}', // required
  apiKey: '{key}', // required
  region: 'IAD', // required, regions can be found at
  useInternal: false // optional, use to talk to serviceNet from a Rackspace machine
})
rackspace.getCdnContainer('{container}', function (err, container) {
  container.client.setTemporaryUrlKey('{temporaryKey}', function (err) {
    container.client.generateTempUrl(container, '{name}', 'GET', 60, '{temporaryKey}', function (err, url) {
      console.log(url)
    })
  })
})
```

So close, yet so far...

**Comment by grud** [comment]
`generateTempUrl` is working for me with Rackspace Cloud Files, currently.

**Comment by c0bra** [comment]
generateTempUrl is working for me with Rackspace Cloud Files, currently.

**Comment by hboylan** [comment]
I got it to correctly generate URLs for PUT, but I never had success with GET for some reason...

**Comment by rosskukulinski** [comment]
Should now be fixed on master - I'll cut a npm release soon.
