### ISSUE TITLE
Network error for AWS S3 Storage in specific zones

### ISSUE THREAD

**Issue by scaret** [pkgcloud/pkgcloud#386]
When I try to create AWS S3 storage client, I notice that I [should assign the region](https://github.com/pkgcloud/pkgcloud/blob/master/docs/providers/amazon.md#using-storage), which is [not required in AWS S3 SDK](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html) when creating the S3 client instance.

Region is required when creating a bucket, but is optional when operating on bucket objects. 

Moreover, If I assign the region as `ap-northeast-1` and try to getContainers, I'll get a networking error. 

```
{ [NetworkingError: socket hang up]
  message: 'socket hang up',
  code: 'NetworkingError',
  sslError: undefined,
  region: 'ap-northeast-1',
  hostname: 's3-ap-northeast-1.amazonaws.com',
  retryable: true,
  time: Wed Jan 14 2015 15:47:53 GMT+0800 (China Standard Time) }
```

But I'm sure I have at least a bucket in ap-northeast-1. So it seems that the hostname(or endpoint) is not set correct when region is assigned.

When I remove the region information from options to create pkgcloud storage client, getContainers() will work fine and will get buckets from all the regions including `ap-northeast-1`

**Comment by yogeshtas** [comment]
i have get same issue while creating file in s3
