### ISSUE TITLE
Allow prepending a custom user agent

### ISSUE THREAD

**Issue by everett-toews** [pkgcloud/pkgcloud#394]
Give your users the ability to _prepend_ a custom user agent. So if the existing user agent is

    pkgcloud/1.1.0

Provide a method for your users to easily prepend their own user agent so they can further customize it.

    users-app/0.1.2 pkgcloud/1.1.0 

This will give cloud providers much better insight into how people are using pkgcloud. This needs to be well documented and part of __any__ examples that are written for pkgcloud so people just copy/paste it in.

**Comment by kenperkins** [comment]
Should this just be a string?

For example:

```javascript
client.setCustomUserAgent('users-app/0.1.2');

// complete agent would be users-app/0.1.2 pkgcloud/1.1.0 
```

**Comment by everett-toews** [comment]
Yep.

**Comment by kenperkins** [comment]
I think that'll work for you @everett-toews (see above PR)

**Comment by everett-toews** [comment]
:+1:
