### ISSUE TITLE
openstack storage copy command

### ISSUE THREAD

**Issue by tewlegit** [pkgcloud/pkgcloud#396]
I know this is commented that it's untested, and it indeed does not work, but it's not far off.  Any chance you could update it with this working version in *openstack/storage/file.js*:

```
File.prototype.copy = function (container, destination, callback) {
  var copyOptions = {
    method: 'COPY',
    uri: this.fullPath,
    headers: {
      'DESTINATION': [container, destination].join('/'),
    }
  };

  this.client._request(copyOptions, function (err) {
    return err
      ? callback(err)
      : callback(null, true);
  });
};
```

**Comment by kenperkins** [comment]
Funny that. Take a look at #350.

**Comment by tewlegit** [comment]
my bad, sorry I missed that.  glad to know it's coming!

**Comment by kenperkins** [comment]
No problem! Glad to have people asking for features :smile:
