### ISSUE TITLE
Rackspace orchestration setWait giving refresh error

### ISSUE THREAD

**Issue by dipdeb** [pkgcloud/pkgcloud#398]
I don't know whether this is an issue or not. I am trying to create a stack. The stack is getting created, but I want to wait in the handler when the stack creation status is 'CREATE_IN_PROGRESS'. So, I was using setWait. But it's giving this error.

Code:
var client = pkgcloud.orchestration.createClient({
        provider: 'rackspace',
        username: 'xxxx',
        apiKey: 'xxxx',
        region: 'HKG'
});
var tmpl = "heat_template_version: 2014-10-16\n \nresources:\n  compute_instance:  \n    type: \"OS::Nova::Server\"\n    properties:\n      flavor: 1 GB Performance\n      image: CentOS 5 (PV)\n      name: Single Server Stack";

    client.createStack({
        name: stack,
        timeout: 60,
        template: tmpl
    }, function(err, stack) {
          if (err) {
            console.dir(err.result.error.message);
            return;
        }
        stack.setWait({ status: 'CREATE_COMPLETE' }, 5000, function (err) {
            if (err) {
                console.dir(err);
                return;
            }
            // TODO
        });
           
    });

Error:
/home/xyz/nodejs/Nodejs_test/Nodejs-Sample-master/node_modules/pkgcloud/lib/pkgcloud/core/base/model.js:50
    self.refresh(function (err, resource) {
         ^
TypeError: Object #<Stack> has no method 'refresh'

**Comment by rosskukulinski** [comment]
Hi @dipdeb, thanks for reporting this issue.  I'm not too familiar with the heat stack, but it wouldn't surprise me if the underlying functionality for setWait was not implemented.

@kenperkins / @ycombinator do you know?

**Comment by dipdeb** [comment]
Can anyone direct me what to do?

**Comment by dipdeb** [comment]
Can anyone direct me what to do?

**Comment by dipdeb** [comment]
I have looked for this refresh function. But it's no where to be found.
Can anyone direct me what to do?

**Comment by dipdeb** [comment]
I have looked for this refresh function. But it's no where to be found.
 Can anyone direct me what to do? @kenperkins

**Comment by kenperkins** [comment]
It appears `refresh` needs to be added to the `Stack` model. I'll get right on that.
