### ISSUE TITLE
[Rackspace] Rebuild Server - cannot send flavorRef or other optional parameters

### ISSUE THREAD

**Issue by eastlondoner** [pkgcloud/pkgcloud#414]
According to the Rackspace docs when making the call to rebuild a server a flavorRef is required (there are also optional properties)
http://docs.rackspace.com/servers/api/v2/cs-devguide/content/Rebuild_Server-d1e3538.html

The rebuild command on the compute client does not allow you to send the flavorRef or any of the optional properties 

Despite not setting a flavorRef the rebuild request works but I cannot script rebuilding to a new flavor, nor can I send any of the optional parameters.

**Comment by kenperkins** [comment]
To fix this the "right" way would like involve a semver change. We should maybe author two PRs: One for semver minor, one for semver major.

i.e. `client.rebuildServer(options, function(err, result) { .. });`

**Comment by ycombinator** [comment]
Hi @eastlondoner,

The documentation at http://docs.rackspace.com/servers/api/v2/cs-devguide/content/Rebuild_Server-d1e3538.html is incorrect about `flavorRef` being required. I have asked that it be corrected.

To change the flavor of a Rackspace Cloud Server using pkgcloud, you can use `client.resizeServer(server, flavor, function(err, result) { ... });`. Here, `flavor` could either be a flavor ID or a flavor object. Please note that only Standard Cloud Servers (as opposed to General Purpose, Memory, IO, or Compute Cloud Servers) can be resized.

As for being able to supply other optional parameters to `rebuildServer`, I am working on a PR for that right now.

**Comment by kenperkins** [comment]
@ycombinator are you saying that `flavor` is not actually allowed on rebuild server?

**Comment by kenperkins** [comment]
Disregard my comments above about having to do a SemVer Major release to accommodate this change; @ycombinator clearly had a great idea in mind.

**Comment by ycombinator** [comment]
> @ycombinator are you saying that flavor is not actually allowed on rebuild server?
No, `flavor` is allowed, it is just not _required_, as (incorectly) stated in the Rackspace API documentation. I have asked for that to be corrected.

**Comment by ycombinator** [comment]
Turns out, after consultation with Rackspace PMs, that `flavor` isn't actually allowed on a rebuild server API call. The documentation incorrectly says it is allowed (and required!). We are getting the documentation fixed.

**Comment by eastlondoner** [comment]
Well I've caused a lot of fuss for little reason then (from a pkgcloud point of view)

**Comment by ycombinator** [comment]
Well, you brought to our attention that other optional properties are not being allowed by `rebuildServer`. We are fixing that in PR #415. Thanks :)
