### ISSUE TITLE
Rackspace orchestration deleteStack not working

### ISSUE THREAD

**Issue by dipdeb** [pkgcloud/pkgcloud#418]
When I try to delete a stack through the deleteStack call, the stack is not deleted. To test I passed a wrong 'stack' name, then it's throwing an error saying "The Stack (xyz) could not be found." . Also, why the callback function deleteStack(stack, f(err)) don't have the stack as a parameter like createStack(stack, f(err, stack)). If stack parameter is there then it'd be nice to do something till the deletion is going on. Is it because setWait for deleteStack is not there?
Please, I need deleteStack to function urgently.

**Comment by ycombinator** [comment]
Hi @dipdeb,

I am able to delete a stack successfully like so:

```javascript
var stackName = 'NAME OF STACK TO DELETE';

// Get stack
client.getStack(stackName, function(err, stack) {
  if (err) {
    return console.log(err);
  }

  // Delete it
  client.deleteStack(stack, function(err) {
    if (err) {
      return console.log(err);
    }
    console.log("Successfully deleted stack " + stackName);
  });
});

```

**Comment by ycombinator** [comment]
We are going to fix `deleteStack` so its first argument could be a stack object (as is the case right now) or a stack name.

**Comment by ycombinator** [comment]
> Also, why the callback function deleteStack(stack, f(err)) don't have the stack as a parameter like createStack(stack, f(err, stack)). If stack parameter is there then it'd be nice to do something till the deletion is going on. Is it because setWait for deleteStack is not there?

If I understand your use case correctly, you could achieve it like so:

```javascript
client.deleteStack(stack, function(err) {
  if (err) {
    // Handle error with stack deletion and return
  }
  // Stack successfully deleted. Proceed with whatever
  // you want to do after the stack is deleted.
});

// Stack is being deleted. Do whatever you
// want while the stack is being deleted.
```

**Comment by dipdeb** [comment]
Thanks, it's working.
Cheers!!

**Comment by dipdeb** [comment]
Thanks, it's working.
Cheers!!

**Comment by dipdeb** [comment]
Thanks, it's working.
Cheers!!

**Comment by dipdeb** [comment]
Thanks, it's working.
Cheers!!

**Comment by dipdeb** [comment]
Thanks, it's working but it comes out immediately from the callback.
Status is still DELETE_IN_PROGRESS.

Cheers!!

**Comment by dipdeb** [comment]
I am doing this in the callback function. So, I can wait there and take some action.

client.deleteStack(stack, function(err, success) {
        if (err) {
            try {
                req.io.emit("error", { error: err.result.error.message });
            } catch (error) {
                if (err.code == 'ETIMEDOUT')
                    req.io.emit("error", { error: 'Connection timed out' });
            }
        }
        client.getStack(stack, function (err, stack) {
                if (err) {
                    req.io.emit("error", { error: err.result.error.message });
                    console.dir(err.result.error.message);
                    return;
                }

                stack.setWait({ status: 'DELETE_COMPLETE' }, 5000, function (err) {
                    if (err) {
                        req.io.emit("error", { error: err.result.error.message });
                        console.dir(err);
                        return;
                    }
                   // Stack successfully deleted. Proceed with whatever
                  // you want to do after the stack is deleted.
                });
        });
  });

**Comment by dipdeb** [comment]
I am doing this in the callback function. So, I can wait there and take some action.

          client.deleteStack(stack, function(err, success) {
                    if (err) {
                        try {
                             req.io.emit("error", { error: err.result.error.message });
                        } catch (error) {
                            if (err.code == 'ETIMEDOUT')
                               req.io.emit("error", { error: 'Connection timed out' });
                         }
                   }
                   client.getStack(stack, function (err, stack) {
                          if (err) {
                              req.io.emit("error", { error: err.result.error.message });
                              console.dir(err.result.error.message);
                              return;
                          }

                          stack.setWait({ status: 'DELETE_COMPLETE' }, 5000, function (err) {
                              if (err) {
                                 req.io.emit("error", { error: err.result.error.message });
                                 console.dir(err);
                                 return;
                               }
                               // Stack successfully deleted. Proceed with whatever
                               // you want to do after the stack is deleted.
                           });
                   });
  });

**Comment by ycombinator** [comment]
Awesome! Glad you got it working for your use case by using `setWait`.
