### ISSUE TITLE
How to get temporary upload  url from openstack ?

### ISSUE THREAD

**Issue by rcramu** [pkgcloud/pkgcloud#422]
Hi ,

Is there any support for "Temporary URLs" using pkgcloud for openstack?

I could see the support for the above item for Rackspace in version 0.9.5.

Thanks  in advance.

**Comment by kenperkins** [comment]
This should be supported for Rackspace. It's not enabled for openstack swift.

https://github.com/pkgcloud/pkgcloud/blob/master/lib/pkgcloud/rackspace/storage/client/cdn-containers.js#L358-L428

It's poorly documented, but should work.

Do you need this for Openstack?

**Comment by rcramu** [comment]
Hi Ken,

Thanks for the response, it would be great if you support this for
openstack.

Thanks,
Ramu

**Comment by rcramu** [comment]
Hi Ken,

Any update on this.
Appreciated.
