### ISSUE TITLE
Rackspace Cloud Files Internal ServiceNet Not Working

### ISSUE THREAD

**Issue by winduptoy** [pkgcloud/pkgcloud#437]
Here's my test file that works perfectly:

```javascript
var fs = require('fs');
var pkgcloud = require('pkgcloud');
var rackspace = pkgcloud.storage.createClient({
        provider: 'rackspace',
        username: 'XXXXX',
        apiKey: 'XXXXX',
        region: 'IAD',
        useInternal: false
});

var writeStream = rackspace.upload({
        container: 'my-container',
        remote: 'output.jpg',
});

writeStream.on('success', function(file) { console.log('SUCCESS', file); });

var readStream = fs.createReadStream('file.jpg');
readStream.pipe(writeStream);
```

When I change `useInternal` to `true`, attempting to use internal Rackspace ServiceNet, it won't upload, it just times out.

**Server:** 1GB General Purpose v1, Ubuntu 15.04, IAD Region
**pkgcloud:** tested on 1.1.0 and 1.2.0-alpha.0
**node:** v0.12.2

**Comment by rosskukulinski** [comment]
Sorry you're having problems, @winduptoy.  On a quick glance, the code looks fine.  

Could you hook up an error handler?

```
writeStream.on('error', function (err) {
  console.log('error', err);
});
```

Could you also hook up to the debug events:

```
rackspace.on('log::*', function(message, object) {
  if (object) {
   console.log(this.event.split('::')[1] + ' ' + message)
   console.dir(object);
  }
  else {
    console.log(this.event.split('::')[1]  + ' ' + message);
  }
});
```

I've got an app that does uploads to cloudfiles using service net and public net depending on where its running.  Our code looks just about the same as yours.  

Two questions:
1) I'm assuming the container exists?
2) Does your host have service net enabled?

**Comment by winduptoy** [comment]
@rosskukulinski Thanks for the response. I've included the output below.

1. Container definitely exists. It works just fine when `useInternal` is disabled.
2. I might be doing it wrong, but as far as I can tell, ServiceNet is enabled.

![screen shot 2015-05-03 at 8 34 56 pm](https://cloud.githubusercontent.com/assets/270504/7447728/7a1ab914-f1d4-11e4-8880-221429cd9525.png)

**`useInternal == false`**
trace Provider Authentication Response
{ href: 'https://identity.api.rackspacecloud.com/v2.0/tokens',
  method: 'POST',
  headers: 
   { server: 'nginx',
     date: 'Mon, 04 May 2015 00:37:58 GMT',
     'content-type': 'application/json',
     'transfer-encoding': 'chunked',
     connection: 'close',
     vary: 'Accept, Accept-Encoding, X-Auth-Token',
     'front-end-https': 'on' },
  statusCode: 200 }
trace Selected service url
{ serviceUrl: 'https://storage101.iad3.clouddrive.com/v1/MossoCloudFS_906722',
  options: 
   { region: 'IAD',
     serviceType: 'object-store',
     useInternal: false,
     useAdmin: undefined } }
trace Creating Authenticated Proxy Request
trace Sending (non-callback) client request
{ method: 'PUT',
  headers: 
   { 'content-type': 'application/javascript',
     'x-auth-token': 'XXXX',
     'User-Agent': 'nodejs-pkgcloud/1.2.0-alpha.0' },
  strictSSL: true,
  json: true,
  uri: 'https://storage101.iad3.clouddrive.com/v1/MossoCloudFS_906722/my-container-name/output.js' }
trace Creating Authenticated Request
trace Sending client request
{ method: 'HEAD',
  headers: 
   { 'x-auth-token': 'XXXXX',
     'User-Agent': 'nodejs-pkgcloud/1.2.0-alpha.0' },
  strictSSL: true,
  qs: { format: 'json' },
  json: true,
  uri: 'https://storage101.iad3.clouddrive.com/v1/MossoCloudFS_906722/slimvoice-logos-dev/output.js' }
debug HEAD: https://storage101.iad3.clouddrive.com/v1/MossoCloudFS_906722/slimvoice-logos-dev/output.js
trace Provider Response
{ href: 'https://storage101.iad3.clouddrive.com/v1/MossoCloudFS_906722/my-container-name/output.js?format=json',
  method: 'HEAD',
  headers: 
   { 'content-length': '292',
     'accept-ranges': 'bytes',
     'last-modified': 'Mon, 04 May 2015 00:37:59 GMT',
     etag: 'c8bd28c1109e05fe06bfdd674cce2144',
     'x-timestamp': '1430699878.76542',
     'content-type': 'application/javascript',
     'x-trans-id': 'tx115ac3c6c32c4c66bef2a-005546bf67iad3',
     date: 'Mon, 04 May 2015 00:37:59 GMT',
     connection: 'close' },
  statusCode: 200 }
SUCCESS { _events: {},
  newListener: false,
  _conf: { delimiter: '::', wildcard: true },
  delimiter: '::',
  wildcard: true,
  listenerTree: {},
  client: 
   { _events: {},
     newListener: false,
     _conf: { delimiter: '::', wildcard: true },
     delimiter: '::',
     wildcard: true,
     listenerTree: { log: [Object] },
     config: 
      { provider: 'rackspace',
        username: 'XXXXX',
        apiKey: 'XXXXX',
        region: 'IAD',
        useInternal: false,
        authUrl: 'https://identity.api.rackspacecloud.com',
        identity: [Object],
        useServiceCatalog: true,
        earlyTokenTimeout: 300000 },
     authUrl: 'https://identity.api.rackspacecloud.com',
     provider: 'rackspace',
     region: 'IAD',
     tenantId: undefined,
     version: 'v2.0',
     before: [ [Function], [Function] ],
     _identity: 
      { options: [Object],
        name: 'RackspaceIdentity',
        basePath: '/v2.0/tokens',
        useServiceCatalog: true,
        _events: {},
        newListener: false,
        _conf: [Object],
        delimiter: '::',
        wildcard: true,
        listenerTree: [Object],
        event: 'log::trace',
        token: [Object],
        serviceCatalog: [Object],
        user: [Object],
        raw: [Object] },
     _serviceUrl: 'https://storage101.iad3.clouddrive.com/v1/MossoCloudFS_906722',
     ...
     serviceType: 'object-store',
     cdnServiceType: 'rax:object-cdn',
     event: 'log::trace' },
  metadata: {},
  container: 'my-container-name',
  name: 'output.js',
  etag: 'c8bd28c1109e05fe06bfdd674cce2144',
  contentType: 'application/javascript',
  lastModified: Mon May 04 2015 00:37:59 GMT+0000 (UTC),
  bytes: 292,
  size: 292 }
```

**`useInternal == true`**
```
trace Provider Authentication Response
{ href: 'https://identity.api.rackspacecloud.com/v2.0/tokens',
  method: 'POST',
  headers: 
   { server: 'nginx',
     date: 'Mon, 04 May 2015 00:32:30 GMT',
     'content-type': 'application/json',
     'transfer-encoding': 'chunked',
     connection: 'close',
     vary: 'Accept, Accept-Encoding, X-Auth-Token',
     'front-end-https': 'on' },
  statusCode: 200 }
trace Selected service url
{ serviceUrl: 'https://snet-storage101.iad3.clouddrive.com/v1/MossoCloudFS_906722',
  options: 
   { region: 'IAD',
     serviceType: 'object-store',
     useInternal: true,
     useAdmin: undefined } }
trace Creating Authenticated Proxy Request
trace Sending (non-callback) client request
{ method: 'PUT',
  headers: 
   { 'content-type': 'application/javascript',
     'x-auth-token': 'XXXXX',
     'User-Agent': 'nodejs-pkgcloud/1.2.0-alpha.0' },
  strictSSL: true,
  json: true,
  uri: 'https://snet-storage101.iad3.clouddrive.com/v1/MossoCloudFS_906722/my-container-name/output.js' }
ERROR { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
```

**Comment by rosskukulinski** [comment]
Hi @winduptoy - Unfortunately, that's as far as my knowledge will go.  Let's harass some Rackers to help... cc: @kenperkins @ycombinator

**Comment by kenperkins** [comment]
@rosskukulinski Sadly our pal @ycombinator went to work on Elasticy Searchy things. :grimacing:

**Comment by kenperkins** [comment]
@winduptoy Are you calling service net from the same region as you're talking to? I believe service-net is only for the current region, and doesn't span across regions. For example, an ORD instance can't talk to IAD cloud files over service-net.

**Comment by winduptoy** [comment]
@kenperkins Yes, everything I'm doing is IAD.

**Comment by kenperkins** [comment]
OK, so then I'm really confused. We should write a small isolated test to confirm.

**Comment by kenperkins** [comment]
I just tested this with node `v0.10.36` on IAD. I'm wondering if something is up with `v0.12.2`.

**Comment by kenperkins** [comment]
OK, I was successful with `v0.12.2`. I'm a bit confused what's going on here.

**Comment by winduptoy** [comment]
I've reconfigured my iptables. Could that have something to do with it?

```
*filter
:INPUT DROP [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]

# Accept anything to localhost
-A INPUT -i lo -j ACCEPT

# Accept HTTP and HTTPS traffic
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT

# Accept SSH traffic on port 24
-A INPUT -p tcp -m tcp --dport 24 -j ACCEPT

# Accept already established connections
-A INPUT -i eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT

COMMIT
```

**Comment by kenperkins** [comment]
Ah. That's probably it. Because Service net is a different interface.

You'll probably need something like this, assuming service net is eth1.

```
-A INPUT -i eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT
```

**Comment by winduptoy** [comment]
@kenperkins :+1: Thanks for the support dude.

**Comment by kenperkins** [comment]
Always happy to help. Just glad we worked it out. :tada:
