### ISSUE TITLE
OpenStack Orchestration DELETE commands do not follow redirects - cannot delete stacks

### ISSUE THREAD

**Issue by stu-smith** [pkgcloud/pkgcloud#441]
It seems our implementation of OpenStack redirects stack DELETE requests from the GUID-only variant to a longer URL.

Unfortunately, pkgcloud does not follow these redirectrs during a DELETE, and hence we cannot delete stacks using pkgcloud.

(Deleting using `heat stack-delete <name>` works fine).

Debug/log output (slightly redacted) is shown below:

```
Selected service url

{
    "serviceUrl": "http://orchestration-*snip*:8004/v1/43ea3d1d91b34cc892b5f730c9434b93",
    "options": {
        "region": "emea1",
        "serviceType": "orchestration"
    }
}

Creating Authenticated Proxy Request
Sending client request

{
    "method": "DELETE",
    "headers": {
        "x-auth-token": "7470ecf9cc874dbb94695a16a0f46a99",
        "User-Agent": "nodejs-pkgcloud/1.2.0-alpha.0"
    },
    "strictSSL": true,
    "json": true,
    "uri": "http://orchestration-*snip*:8004/v1/43ea3d1d91b34cc892b5f730c9434b93/stacks/dashboard-ci-emea1"
}

DELETE: http://orchestration-*snip*:8004/v1/43ea3d1d91b34cc892b5f730c9434b93/stacks/dashboard-ci-emea1
Provider Response

{
    "href": "http://orchestration-*snip*:8004/v1/43ea3d1d91b34cc892b5f730c9434b93/stacks/dashboard-ci-emea1",
    "method": "DELETE",
    "headers": {
        "location": "http://orchestration-*snip*:8004/v1/43ea3d1d91b34cc892b5f730c9434b93/stacks/dashboard-ci-emea1/b2bd6d56-0cba-4d43-ae07-1dfe7201498e",
        "content-length": "245",
        "content-type": "text/plain; charset=UTF-8",
        "date": "Tue, 05 May 2015 11:26:14 GMT",
        "connection": "keep-alive"
    },
    "statusCode": 302
}

```

**Comment by kenperkins** [comment]
Interesting. Sounds like we may need to look at the status code and make a follow on request. I'm sorry you had to discover this; PRs welcome :)

**Comment by stu-smith** [comment]
Not a problem; this project is saving me a ton of time accessing OpenStack.

Oddly, the problem only seems to occur when using the `deleteStack("name-of-stack")` variant: if I do a `getStack("name-of-stack")` first, then pass the stack itself into `deleteStack(stack)`, everything works fine.

I'm using `deasync` (which is a bit naughty I know)... not sure if that's a contributory factor. Also please don't rule out user error...

**Comment by stu-smith** [comment]
Apologies, this behaviour only exhibited on the NPM version (1.2.0-alpha.0, about 4 months old at time of writing).

I've since upgraded to the GitHub version, and the issue no longer exists.

**Comment by kenperkins** [comment]
Awesome, glad to hear it!
