### ISSUE TITLE
file.container is the string '[object Object]'

### ISSUE THREAD

**Issue by OrangeDog** [pkgcloud/pkgcloud#445]
Using the 'hp' or 'openstack' provider (haven't check any others), returned file objects have had their container object converted to a string, rendering the property useless.

**Comment by OrangeDog** [comment]
Hmm, not sure what happened, but after deleting and recreating the container, the property is now a correct container object.

**Comment by kenperkins** [comment]
Were you doing a `toString()` on it possibly?

**Comment by OrangeDog** [comment]
No, the code didn't change, and I used the repl to inspect it.
Perhaps I hiccuped earlier and the container actually did have that as a name.
