### ISSUE TITLE
OpenStack nova networks are not supported

### ISSUE THREAD

**Issue by fifieldt** [pkgcloud/pkgcloud#451]
Pkgcloud currently has support for networks implemented using OpenStack's software defined networking service ('neutron').

However, a significant number of deployments do not use this service, and instead rely purely on nova to provide networking.

For those deployments, when they run pkgcloud.network.createClient they get back:

> [Error: Unable to find matching endpoint for requested service]

since it straight away tries to search for a neutron endpoint.

**Comment by fifieldt** [comment]
In terms of implementation, there are two paths forward:
1) make the network module speak both nova and neutron
2) extend the compute module to speak the additional nova calls

The second seems more sane to me, because this way the delineation between services is preserved.

**Comment by fifieldt** [comment]
A couple of of basic features are probably the highest priority:
Security groups: http://developer.openstack.org/api-ref-compute-v2-ext.html#os-security-groups
Floating IPs: http://developer.openstack.org/api-ref-compute-v2-ext.html#os-floating-ips

**Comment by fifieldt** [comment]
I could have just made a newbie error here :)
Looking into the extensions directory eg
./lib/pkgcloud/openstack/compute/client/extensions/floating-ips.js

**Comment by fifieldt** [comment]
Now trying to reconcile the version I'm running with why I don't see the extensions in the client

**Comment by fifieldt** [comment]
1.2.0 alpha, so should be there.

Any hints on using extensions? :)

**Comment by kenperkins** [comment]
It should be on the client, if you're using `1.2.0-alpha.0`.

```javascript
client.getFloatingIps(function(err, ips) {

});
```

etc.

What aren't you seeing? I assume you're using the plain `openstack` provider?

**Comment by kenperkins** [comment]
Here's where the client pulls in all of the extensions:

https://github.com/pkgcloud/pkgcloud/blob/10ac5b5f3cec1dbe159ce9ec2c593f398231cc45/lib/pkgcloud/openstack/compute/client/extensions/index.js#L25-31

**Comment by fifieldt** [comment]
well, I don't know how I screwed that one up - it's working now, but I honestly didn't get the extensions when I was trying (admittedly at midnight) last night. Let's nuke this issue to clean up your tracker while I fix my n00bness :)

**Comment by kenperkins** [comment]
Was it possible you were looking at the rackspace provider? We don't have those extensions enabled...

**Comment by kenperkins** [comment]
I used the `os-floating-ip` code against HP Cloud during my workshop at SXSW last year, so I'm pretty sure they've been around for a while :)

**Comment by kenperkins** [comment]
That said, the `networks` provider was added for last years OS Summit in Paris. It's much newer.

**Comment by fifieldt** [comment]
This is against a vanilla-ish cloud, using the openstack provider. I was clearly wrong with the initial report, so I'll chalk this up to my node.js inexperience and hope you'll forgive me!

**Comment by kenperkins** [comment]
Just happy to help. Sorry with the delay in replying.
