### ISSUE TITLE
OpenStack security groups - no deleteRule

### ISSUE THREAD

**Issue by fifieldt** [pkgcloud/pkgcloud#453]
Looking at

https://github.com/pkgcloud/pkgcloud/blob/master/lib/pkgcloud/openstack/compute/client/extensions/security-group-rules.js 

it seems like there is no deleteRule method.

I checked upstream over at https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/contrib/security_groups.py#L302 and it is indeed there, but sadly missing from the documentation site.

**Comment by kenperkins** [comment]
Often we implement against the documentation, not the implementation. That's probably why we're missing `DELETE`. 

PRs welcome!

**Comment by DonSchenck** [comment]
Excuse my ignorance, but what is this?:

https://github.com/pkgcloud/pkgcloud/blob/master/lib/pkgcloud/openstack/network/client/securityGroupRules.js#L123

**Comment by kenperkins** [comment]
That looks like what @fifieldt was looking for. I didn't implement that code, sorry for not being 100% familiar with it!

**Comment by fifieldt** [comment]
thanks @DonSchenck  - that one is for neutron though. There's also basically the same call in the nova API, which is where I need it :) The code you've linked is probably quite re-usable

**Comment by fifieldt** [comment]
It looks like this was solved in 2015. Closing issue :)
