### ISSUE TITLE
Typo in Openstack createSecurityGroup

### ISSUE THREAD

**Issue by jbemmel** [pkgcloud/pkgcloud#454]
In pkgcloud/lib/pkgcloud/openstack/network/client/securityGroups.js the createSecurityGroup code uses 'body.securityGroup' in the callback, this should be 'body.security_group' ( line 146 )

**Comment by vivekzhere** [comment]
Hi any update on this. Still network.createSecurityGroup is  not passing the details of the security group created to the callback. The typo is still there.

**Comment by rosskukulinski** [comment]
merged
