### ISSUE TITLE
Resize server (Rackspace Cloud)

### ISSUE THREAD

**Issue by amolkedar** [pkgcloud/pkgcloud#462]
Can i resize server using this API? i didn't see it in the documentation

**Comment by underbyte** [comment]
I don't believe you can with this module but you can do it with Rackspace API or control panel.

**Comment by bbhands** [comment]
You can use `client.resizeServer(server, flavor, callback)`, where `flavor` could be an object of `Flavor` or simply a `flavorId`.

**Comment by amolkedar** [comment]
ok great i am going to try this now

**Comment by amolkedar** [comment]
Yes thanks that worked
