### ISSUE TITLE
Local filesystem storage provider

### ISSUE THREAD

**Issue by dmyers** [pkgcloud/pkgcloud#464]
Is there any plan for this or is it supported by chance?

In the past I [made something similar](https://github.com/dmyers/laravel-storage) and it's very useful to have local as an option for development and then a environment flag to switch to say S3 in production.

It looks like it would be useful to others based on some things I found...

https://github.com/strongloop/loopback-component-storage/blob/master/lib/providers/filesystem/index.js
https://github.com/bipio-server/bipio/tree/master/src/modules/cdn
http://stackoverflow.com/questions/14382512/nodejs-any-file-system-provider

**Comment by amok** [comment]
+1

**Comment by rafis** [comment]
https://github.com/Jemsoft/filesystem-storage-pkgcloud
