### ISSUE TITLE
client.upload throws un unhandled error

### ISSUE THREAD

**Issue by akras14** [pkgcloud/pkgcloud#481]
I believe there is a bug in:
https://github.com/pkgcloud/pkgcloud/blob/master/lib/pkgcloud/openstack/storage/client/files.js#L124

The following code is being called:
```javascript
writableStream = this._request(uploadOptions);
```
which in turn calls: 

https://github.com/pkgcloud/pkgcloud/blob/master/lib/pkgcloud/openstack/client.js#L192

```javascript
Client.prototype._request = function (options, callback) {

  var self = this;
  if (!self._isAuthorized()) {
    self.emit('log::trace', 'Not-Authenticated, inlining Auth...');
    var proxyStream = through();
    proxyStream.pause();

    self.auth(function (err) {
      if (err) {
        self.emit('log::error', 'Error with inline authentication', err);
        return errs.handle(err, callback); // <--- PROBLEM
      }
//...
```

This creates a problem, since `writableStream = this._request(uploadOptions);` does not pass a callback.

The code for `errs.handle` is bellow:

```javascript
exports.handle = function (error, callback, stream) {

  error = exports.create(error);

  if (typeof callback === 'function') {
    callback(error);
  }

  if (typeof callback !== 'function' || stream) {
    var emitter = stream || callback || new events.EventEmitter();
    process.nextTick(function () { emitter.emit('error', error); });
    return emitter;
  }
};
```

As you can see, errs.handle expects a callback or a stream. If neither is provided it creates a `new events.EventEmitter()` and emits error on it on a next tick.

Since that new event emitter does not have any error listeners Node 4 throws an error, that cannot be caught by implementations using your library.

A proposed solution is to modify [openstack/storage/client/files.js](https://github.com/pkgcloud/pkgcloud/blob/master/lib/pkgcloud/openstack/storage/client/files.js#L124) as follows:

```javascript
writableStream = this._request(uploadOptions, function(err){
  if(err){
    proxyStream.emit('error', err);
  }
});
```

That what users of `client.upload` can subscribe to the error and handle it properly.

**Comment by Zertz** [comment]
I'm guessing this is a problem with storage providers in general as we're running into the same issue with Azure.

**Comment by akras14** [comment]
Simple example to reproduce the error.

Looks like very upload is making 2 identity calls, hitting the limit of 100 request per minute pretty fast, which throws an unhandled exception, even though I have a valid error subscriber.

```javascript
var pkgcloud = require('pkgcloud');
var fs = require('fs');

var client = pkgcloud.storage.createClient({
  provider: 'rackspace',
  username: '{username}',
  apiKey: '{apiKey}',
  region: '{region}'
});

function uploadFile(count){
  var source = fs.createReadStream('./deleteme.txt');
  var result = client.upload({
    container: 'delete-me-testing',
    remote: 'somefile' + count + '.txt'
  });
  result.on('error', function(err){ //<-- Valid error subscriber
    console.log(err);
  });
  result.on('success', function(err){
    console.log("Success " + count);
  });
  source.pipe(result);
}

//Kick off the test, may be try a bigger number instead of 51, like a 100
for(var i = 0; i < 51; i++){
  uploadFile(i);
}

process.on('uncaughtException', function(err) {
  console.log('Caught exception, which was not handled: ' + err);
});
```

**Comment by BobDickinson** [comment]
PR #484 merged and unit tests passing.
