### ISSUE TITLE
1.3.0 release

### ISSUE THREAD

**Issue by BobDickinson** [pkgcloud/pkgcloud#497]
The current plan is to release a 1.3.0 and publish to npm in the very near future.  This release will consist of the head of master plus a set of very low-risk PRs.  We're primarily trying to capture the PRs done in the past year and get them released.  

The higher risk PRs and open issues will be reviewed for the next release.

**Comment by BobDickinson** [comment]
Just merged low-risk PRs: #496, #484, #456, #447, #444, and #442

**Comment by kenperkins** [comment]
:+1: 

Been on vacation and sick for last week! Love seeing you jump in here and I'm going to figure out how to help.

**Comment by BobDickinson** [comment]
I completed the review of changes between the 1.2.0 release and now

* OpenStack identity v3 (keystone) support, Issue #367, #477, PR #461
* OpenStack cancel client download, Issue #379, PR #416
* OpenStack improved directory support for getFiles, PR #390
* Add support for prepending a custom user agent, Issue #394, PR #395
* OpenStack fixed storage copy function, Issue #396 , PR #350
* OpenStack allow non-strict SSL, PR #397 
* Adding a refresh method on the stack model, Issue #398, PR #402
* Google storage return metadata in success handler, Issue #400, PR #401
* OpenStack added template outputs field to stack, PR #403
* Amazon fixes to AWS config, Issue #406, PR #407, #409,
* Added support for nestedDepth option to stack getResources method, Issue #410, PR #411
* Added support for networking security groups, security group rules, PR #412
* Allow passing options to rebuildServer, Issue #414, PR #415
* Allow deleteStack to accept stack object or stack name, Issue #418, PR #420
* Amazon createServer: use pluralized keys for SecurityGroups/SecurityGroupIds, Issue #432, PR #433
* RackSpace, OpenStack add enableRootUser and listRootStatus, PR #438
* Amazon storage added cache control support to s3 buckets, PR #447
* OpenStack compute added deleteRule, PR #456
* DigitalOcean ported provider to APIv2, PR #470
* OpenStack handle request errors in client.upload flow, Issue #481, PR #484
* OpenStack added adminPass attribute to createServer, PR #486
* Amazon added AWS specific options for cache control and file encryption, PR #496
* Misc doc fixes, PR #417, #426, #429, #442, #444, #449

**Comment by BobDickinson** [comment]
OK, so I think we should be ready to take #469 and #499 after a quick review by someone other than me (@indexzero, @kenperkins).  I will then make the buffer change from #469 to Azure download (making that change on the PR itself is a little beyond my GitFu).  Once done, I'll update the CHANGELOG.md and then I would say we have a 1.3.0 RC.

**Comment by kenperkins** [comment]
I'll start reviewing #469 now :coffee:

**Comment by rosskukulinski** [comment]
:clap: :clap: for @BobDickinson

**Comment by BobDickinson** [comment]
Given that there is a workaround for #469 (and a longer term fix coming), I think we've decided not to include it in 1.3.0.

I'm of the opinion that we are ready for a 1.3.0 release.

**Comment by kenperkins** [comment]
Last call for objections, otherwise I'm ready to publish. Thanks again @BobDickinson for all your work getting us back on track.

**Comment by kenperkins** [comment]
Specifically, I plan on publishing Monday morning at 10am pacific unless there are any dissenting comments.

**Comment by kenperkins** [comment]
I'm a little behind but this should go out today.

**Comment by kenperkins** [comment]
```
/Volumes/Data/src/pkgcloud [master] $ npm publish
+ pkgcloud@1.3.0
```

**Comment by kenperkins** [comment]
:tada:
