### ISSUE TITLE
Can't upload file above 56359 bytes (16K) to openstack

### ISSUE THREAD

**Issue by arivatibm** [pkgcloud/pkgcloud#503]
my files are cut off when I upload using the pkgcloud-bluemix-objectstorage that is based on the pkgcloud source code

**Comment by kenperkins** [comment]
Can you point me to the source for this package? I can't figure out what's going on without seeing what it's doing.

**Comment by arivatibm** [comment]
nevermind - issue was resolved (upload was ok , the download had a bug)
 
                                                                        Regards,
                         
                        Ari Volcoff                        Research Staff Member                        Smart Wearable and IoT Solutions - Smarter Business Solution Group                        IBM - Haifa Research Lab                                                                         
                                                                                                                                Mobile: +972-58-4168357 | Phone: +972-4-8281319                        E-mail: ARIV@il.ibm.com                        
 
 
----- Original message -----From: Ken Perkins <notifications@github.com>To: pkgcloud/pkgcloud <pkgcloud@noreply.github.com>Cc: Ari Volcoff/Haifa/IBM@IBMILSubject: Re: [pkgcloud] Can't upload file above 56359 bytes (16K) to openstack (#503)Date: Fri, Mar 25, 2016 5:38 AM 
Can you point me to the source for this package? I can't figure out what's going on without seeing what it's doing.
—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub
