### ISSUE TITLE
Cannot find module './pkgcloud/core/compute'

### ISSUE THREAD

**Issue by FrenchBen** [pkgcloud/pkgcloud#512]
Following along with the ReadMe, I have:

```
var pkgcloud = require('pkgcloud');
var client = pkgcloud.storage.createClient({
   provider: 'amazon',
   keyId: 'your-access-key-id', // access key id
   key: 'your-secret-key-id', // secret key
   region: 'us-west-2' // region
});
```

Loading it in the browser window, I get the following error:
`Cannot find module './pkgcloud/core/compute'`

I'm not trying to load any compute client and npm showed it installed the modules as well:

```
pkgcloud@1.3.0 node_modules/pkgcloud
├── eventemitter2@0.4.14
├── ip@0.3.3
├── url-join@0.0.1
├── underscore@1.6.0
├── mime@1.2.11
├── async@0.9.2
├── fast-json-patch@0.5.6
├── filed@0.1.0
├── s3-upload-stream@1.0.7
├── errs@0.3.2
├── qs@1.2.2
├── xml2js@0.1.14 (sax@1.2.1)
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.34)
├── request@2.40.0 (forever-agent@0.5.2, aws-sign2@0.5.0, tunnel-agent@0.4.2, oauth-sign@0.3.0, stringstream@0.0.5, json-stringify-safe@5.0.1, tough-cookie@2.2.2, mime-types@1.0.2, qs@1.0.2, node-uuid@1.4.7, http-signature@0.10.1, form-data@0.1.4, hawk@1.1.1)
├── gcloud@0.10.0 (extend@1.3.0, node-uuid@1.4.7, stream-events@1.0.1, duplexify@3.4.3, gapitoken@0.1.5, protobufjs@3.8.2)
└── aws-sdk@2.3.4 (sax@1.1.5, xml2js@0.4.15, jmespath@0.15.0, xmlbuilder@2.6.2)
```

What am I missing?

**Comment by RavDanny** [comment]
@FrenchBen - did you resolve this issue?

I'm having it as well.

**Comment by FrenchBen** [comment]
@RavDanny Unfortunately I moved on to a different library :\

**Comment by RavDanny** [comment]
Oh. Did you find an equivalent package?

**Comment by FrenchBen** [comment]
I didn't find an npm package that was comparable. I ended up using the AWS GO SDK

**Comment by RavDanny** [comment]
Ok. Thanks

**Comment by RavDanny** [comment]
I worked out what the problem was in my case.

Apparently some of the package's dependencies can only be imported on the server (e.g. fs). I was importing them from within a Meteor shared file (both server and client). Once I ensured they were only being imported on the server, the problem disappeared.

**Comment by FrenchBen** [comment]
@RavDanny good to know! thanks for sharing your solution. 

Closing this since there isn't much activity on it.

**Comment by drzraf** [comment]
FYI https://github.com/pkgcloud/pkgcloud/issues/694
