### ISSUE TITLE
Large files fail to download

### ISSUE THREAD

**Issue by chaddjohnson** [pkgcloud/pkgcloud#522]
When attempting to download large files, I get the error shown here:

<img width="1026" alt="screen shot 2016-07-01 at 1 29 47 am" src="https://cloud.githubusercontent.com/assets/676134/16513692/3b435e0c-3f2c-11e6-9b3b-b2dbd2bf4ed8.png">

The code I am using is as follows:

```javascript
var pkgcloud = require('pkgcloud');
client = pkgcloud.providers.openstack.storage.createClient({
    provider: 'openstack',
    username: config.storage.username,
    password: config.storage.password,
    authUrl: config.storage.authUrl,
    version: 1
});
client.auth(function(error) {
    tempFilePath = path.join(os.tmpdir(), data.filename);

    client.download({
        container: config.storage.containerName,
        remote: data.filename,
        local: tempFilePath
    }, function(error, result) {
        taskCallback(error);
    });
});
```

This is because toString() is called on a buffer that is above `kStringMaxLength` for `buffer`. See https://github.com/nodejs/node/issues/3175.

I found a workaround which involves using `http-request` instead of `client.download()` because I believe `http-request` downloads in chunks:

```javascript
var pkgcloud = require('pkgcloud');
var http = require('http-request');

client = pkgcloud.providers.openstack.storage.createClient({
    provider: 'openstack',
    username: config.storage.username,
    password: config.storage.password,
    authUrl: config.storage.authUrl,
    version: 1
});
client.auth(function(error) {
    if (error) {
        return taskCallback(error);
    }

    var tempFilePath = path.join(os.tmpdir(), data.filename);
    var options = {
        url: client._identity._storageUrl + '/' + config.storage.containerName + '/' + data.filename,
        headers: {'X-Auth-Token': client._identity.token.id}
    };
    http.get(options, tempFilePath, function(err, res) {
        taskCallback(error);
    });
});
```

I recommend fixing this in core `pkgcloud`. This definitely affects openstack storage, and it likely affects other storage adapters.

**Comment by BobDickinson** [comment]
We ran into this on #469 - you might see the comments there if interested.  The summary is that for large file downloads, you should never use the callback form of download() - as that is what is triggering the attempted conversion of the downloaded content to a string.  If you think about what's going on there, it makes sense - that callback, on success, is expecting the downloaded contents (decoded, presumably as a string), which when humongous, is going to be a problem no matter what you do.

You should instead use the stream interface any time the downloaded file may be large (I just use the stream interface in all cases - but there may be special use cases of typically small text files where the callback method is appropriate for people).  But anyway, for potentially large files, use streams.  Handle the 'error' event on the stream to get any errors.  The docs on this could be a lot better.

**Comment by chaddjohnson** [comment]
Nice -- that works. Thank you! Here is the code I used:

```javascript
var fs = require('fs');
var pkgcloud = require('pkgcloud');

client = pkgcloud.providers.openstack.storage.createClient({
    provider: 'openstack',
    username: config.storage.username,
    password: config.storage.password,
    authUrl: config.storage.authUrl,
    version: 1
});

var stream = fs.createWriteStream('/tmp/largefile.csv');

stream.on('error', function() {
    console.log('error');
});
stream.on('finish', function() {
    console.log('done');
});

client.auth(function(error) {
    client.download({
        container: config.storage.containerName,
        remote: 'data.csv'
    }).pipe(stream);
});
```
