### ISSUE TITLE
Upgrade to latest "request" package

### ISSUE THREAD

**Issue by demsey2** [pkgcloud/pkgcloud#531]
pkgcloud depends on "request" package version 2.40.x, the "request" package in that version depends on vulnerable "hawk" package, the latest "request" fixes that but package.json for this module has to be updated 

more info here
https://nodesecurity.io/advisories/77

**Comment by saggafarsyad** [comment]
+1

**Comment by mattgrande** [comment]
Fixed in version 1.5.0; This can be closed.
