### ISSUE TITLE
Error (400): Bad Request / get_version_v3() got an unexpected keyword argument

### ISSUE THREAD

**Issue by soichih** [pkgcloud/pkgcloud#532]
Hello. I am just trying to see if I can use pkgcloud for our openstack instance, and I have following test code.

```
const pkgcloud = require('pkgcloud');
//const os = require('os');

const client = pkgcloud.compute.createClient({
    provider: 'openstack',
    username: process.env.OS_USERNAME,
    password: process.env.OS_PASSWORD,
    authUrl: 'https://my.openstack.com:3000',
    basePath: 'v3',
});

client.getFlavors(function(err, flavors) {
    console.dir(err);
});
```

This outputs following error message.

```
{ [Error: Error (400): Bad Request]
  name: 'Error',
  failCode: 'Bad Request',
  statusCode: 400,
  href: 'https://jblb.jetstream-cloud.org:35357/v3',
  method: 'POST',
  headers: 
   { date: 'Thu, 06 Oct 2016 17:13:34 GMT',
     server: 'Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5',
     vary: 'X-Auth-Token',
     'x-openstack-request-id': 'req-fc405819-536b-4158-b6e8-afa0152bd295',
     'content-length': '121',
     connection: 'close',
     'content-type': 'application/json' },
  result: 
   { error: 
      { message: 'get_version_v3() got an unexpected keyword argument \'auth\'',
        code: 400,
        title: 'Bad Request' } } }
```

Does pkgcloud support OpenStack API v3.6?

**Comment by BobDickinson** [comment]
I'm not sure about 3.6 specifically.  It does support v3 auth as of PkgCloud v1.3.0.

v3 auth was added in #477 and there is a docs bug for v3 support #528 (along with a PR).

The config for v3 is different than v2, so I'd suggest looking at that docs bug.  My config (for BlueMix using v3 auth) is:

    {
        "provider": "openstack",
        "authUrl": "https://identity.open.softlayer.com/",
        "region": "xxxx",
        "tenantId": "xxxx",
        "username": "xxxx",
        "password": "xxxx,
        "domainId": "xxxx",
        "domainName": "xxxx",
        "keystoneAuthVersion": "v3"
    }

**Comment by soichih** [comment]
@BobDickinson  Thanks for the quick response.

I've looked at `/pkgcloud/lib/pkgcloud/openstack/context/identity.js` and I believe I've populated all necessary config options. Here is the dump of my `self._authenticationPayload`

```
{
    "auth": {
        "identity": {
            "methods": [
                "password"
            ],
            "password": {
                "user": {
                    "password": "mypassword",
                    "name": "myuserid",
                    "domain": {
                        "id": "tacc"
                    }
                }
            }
        },
        "scope": {
            "project": {
                "id": "MY-PROJECTID123",
                "domain": {
                    "name": "tacc"
                }
            }
        }
    }
}

```

Does this look right?

Anyway, I am still seeing an error message.

```
 [Error: Error (401): Unauthorized]
  name: 'Error',
  failCode: 'Unauthorized',
  statusCode: 401,
  href: 'https://our.openstack.org:35357/v3/auth/tokens',
  method: 'POST',
  headers: 
   { date: 'Thu, 06 Oct 2016 18:24:09 GMT',
     server: 'Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5',
     vary: 'X-Auth-Token',
     'x-openstack-request-id': 'req-bdc6aa8a-c99e-46ba-bd37-isthissensitive?',
     'www-authenticate': 'Keystone uri="https://our.openstack.org:35357"',
     'content-length': '114',
     connection: 'close',
     'content-type': 'application/json' },
  result: 
   { error: 
      { message: 'The request you have made requires authentication.',
        code: 401,
        title: 'Unauthorized' } } }

```

I am not sure why I need to be authenticated to *get* the initial authentication token.. Is it using a wrong authURL?

**Comment by soichih** [comment]
OK I was finally able to get the client configuration to work.

I basically had to use "tenantName" instead of "tenantID", and "projectDomainName" as well as "region" which I had to find by digging into the /openstack/context/service.js..

**Comment by guankai** [comment]
@soichih I met the problem same as you, I use BobDickinson's config, but I do not know the 'domainId' and 'domainName' value,can you show me that ,thank you

**Comment by harishvarma8055** [comment]
@soichih Was does tenantName means here.I dont see any such..Can you please reply what fixed the issue exactly

**Comment by soichih** [comment]
```
const client = pkgcloud.compute.createClient({
//console.dir({
    provider: 'openstack',

    authUrl: 'https://your.openstack.org:35357/', 

    region: "RegionOne",
    tenantName: process.env.OS_PROJECT_NAME,

    username: process.env.OS_USERNAME,
    password: process.env.OS_PASSWORD,

    domainName: process.env.OS_USER_DOMAIN_NAME,

    projectDomainName: process.env.OS_PROJECT_DOMAIN_NAME,
    keystoneAuthVersion: 'v3',
});

```

```
export OS_PROJECT_DOMAIN_NAME=yourdomain
export OS_USER_DOMAIN_NAME=yourdomain
export OS_PROJECT_NAME=TG-YOURPROJECT123 
export OS_USERNAME=yourusername
export OS_PASSWORD=yourpassword
export OS_AUTH_URL=https://your.openstack.org:35357/v3 
export OS_IDENTITY_API_VERSION=3
```

I hope this helps!

**Comment by harishvarma8055** [comment]
@soichih Thanks.But didnt worked this is my code..Iam still getting the same old 401 error which u got earlier..Can u please have a look at this


`var express = require('express');
var cfenv = require('cfenv');
var rp = require('request-promise-native');
var request = require('request');
var pkgcloud = require('pkgcloud');
var fs = require('fs');
var app = express();
app.set('views', __dirname + '/views');
app.engine('html', require('ejs').renderFile);
//Creating a config object with object storage details
var config = {};
config.provider = "openstack";
config.region= 'dallas';
config.useServiceCatalog = true;
config.useInternal = false;
config.keystoneAuthVersion =  "v3",
config.userId = "ea7f2648e326479eaddb3a4140926b73";
config.password = "pS_f-.y5?A~5AZcN";
config.tenantName  = "367e41f67d154f13a7eef6c7f2b082cf";
config.domainId = "fbfd3ceb2f6e4a6db9a0b97ff0e64c01";
config.domainName = "1290021";
config.authUrl = 'https://identity.open.softlayer.com';
config.project = "object_storage_c336581d_f7a5_4a32_99b7_af3229b1f96c";
config.role = "admin";
var SOFTLAYER_ID_V3_AUTH_URL = "https://lon-identity.open.softlayer.com/v3/auth/tokens";

config.auth = {
	provider : "openstack",
	forceUri : "https://lon-identity.open.softlayer.com/v3/auth/tokens",
	interface: "internal",
	"identity": {
		"methods": [
		"password"
		],
		"password": {
			"user": {
				"id": config.userId,
				"password": config.password
			}
		}
	},
	"scope": {
		"project": {
			"name": config.tenantName,
			"domainName":config.domainName
		}
	}
};



var storageClient = pkgcloud.storage.createClient(config);
console.log("asdasHere");
app.post('/uploadfile',function(req,res){
	

	storageClient.createContainer({
		name: 'mycontainer'
	}, function (err, container) {
		if (err) {
			console.error("first errror",err);
		}else{
			var containerName = req.headers.container;
			console.log("cacsa",containerName)
			var myFile = fs.createReadStream(__dirname,'/uploads/manifest.txt');
			var upload = storageClient.upload({
				container: containerName,
				remote: 'file.txt'
			});
			upload.on('error', function(err) {
				console.error("errroror",err);
			});
			upload.on('success', function(file) {
				console.log(file.toJSON());
			});
			myFile.pipe(upload);

		//}
	//})

}});


});

app.listen(process.env.PORT || 3000);

exports.app = app`

**Comment by shubhamrsangle** [comment]
> const client = pkgcloud.compute.createClient({
> //console.dir({
>     provider: 'openstack',
> 
>     authUrl: 'https://your.openstack.org:35357/', 
> 
>     region: "RegionOne",
>     tenantName: process.env.OS_PROJECT_NAME,
> 
>     username: process.env.OS_USERNAME,
>     password: process.env.OS_PASSWORD,
> 
>     domainName: process.env.OS_USER_DOMAIN_NAME,
> 
>     projectDomainName: process.env.OS_PROJECT_DOMAIN_NAME,
>     keystoneAuthVersion: 'v3',
> });
> 
> 
> export OS_PROJECT_DOMAIN_NAME=yourdomain
> export OS_USER_DOMAIN_NAME=yourdomain
> export OS_PROJECT_NAME=TG-YOURPROJECT123 
> export OS_USERNAME=yourusername
> export OS_PASSWORD=yourpassword
> export OS_AUTH_URL=https://your.openstack.org:35357/v3 
> export OS_IDENTITY_API_VERSION=3
> 
> I hope this helps!

Thank you very much for your help, it helped me alot
