### ISSUE TITLE
request@2.40.x has vulnerability

### ISSUE THREAD

**Issue by thanh-taro** [pkgcloud/pkgcloud#542]
The `request@2.40.x` uses `hawk@1.1.1` which has [Regular Expression Denial of Service](https://nodesecurity.io/advisories/77). Please update dependencies to fix it.

**Comment by ghamaide** [comment]
+1

**Comment by rdubigny** [comment]
+1

**Comment by github23** [comment]
+1

**Comment by cse-tushar** [comment]
+1

**Comment by ShamanisTe** [comment]
+1

**Comment by mattgrande** [comment]
Fixed by #587

**Comment by mattgrande** [comment]
Fixed in version 1.5.0; This can be closed.
