### ISSUE TITLE
Accessing openstack api and got an error with self signed certificate message

### ISSUE THREAD

**Issue by phoenix2005f** [pkgcloud/pkgcloud#559]
I am not familiar with openstack.

I used official example to create vm and try  to access openstack api authentication.

open stack environment was set https.

var client = pkgcloud.compute.createClient({
  **provider**: 'openstack',
  **username**: 'username',
  **password**: 'my_password',
  **region**: 'RegionOne', //default for DevStack, might be different on other OpenStack distributions
  **authUrl**: 'https:// ip :5000/v2.0'
});

I got an error
Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }

**Comment by rosskukulinski** [comment]
Is your OpenStack cluster leveraging self-signed certificates?  Node.js by default does not allow connecting to untrusted certificates.

You should look at leveraging NODE_TLS_REJECT_UNAUTHORIZED as a process.env to disable the check.  NOTE: From a security perspective, this is not recommended.
