### ISSUE TITLE
pkgClient download method does not provide callback function

### ISSUE THREAD

**Issue by indu-s** [pkgcloud/pkgcloud#583]
Hi,
I am using pkgcloud package to connect to amazon s3 storage. The "download" method of pkgclient (for amazon S3) does not provide any callback function. Is there any way to find out about the download  status or to gracefully handle any error occurred. 

Thanks in adavance for the help.

Note: 'aws-sdk' provide callback for "getObject" method (which is called  by pkgcloud to download file). Also, in earlier versions of pgcloud , callback was available.

**Comment by Marak** [comment]
@indu-s 

It's a streaming interface. You'll have to add stream handlers for events like `error`.

If you really wanted a callback interface I believe you would have to buffer the stream into memory and wrap that in an async interface.  I've been able to do this before using `stream-buffers` and `through2` library with pkgcloud's `download` method.
