### ISSUE TITLE
Upload file to AWS S3 with AWS EC2 Role instead of user credentials

### ISSUE THREAD

**Issue by danielesalvatore** [pkgcloud/pkgcloud#602]
Hi everyone, 
first of all, thank you very much for the work and your support. 

**Context**: application deployed to Amazon EC2 instance, that can upload/download files from S3 storage. 

From what I see from the documentation, when the library is used to upload files to AWS S3 storage it requires IAM user credentials to authenticate agains the S3 API. Additionally to this authentication method, AWS allows trusted entities to assume roles, such as IAM users, applications, or AWS services such as EC2.

As [best practice](https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#use-roles-with-ec2) AWS suggests to use roles for applications that run on Amazon EC2 instances.

Is pkgcloud compatible with the use of AWS role to interact with S3 storage? If it isn't, do you plan to have this option in the near future?

Thank you very much in advance.

**Comment by jeznag** [comment]
@danielesalvatore I believe you just need to leave accessKey and accessKeyId blank and the S3 SDK will automatically fetch the credentials from the instance metadata service. Have you tried that? It works for me.

**Comment by danielesalvatore** [comment]
Hi @jeznag, thank you for reaching me out! I remember that i gave it a try at the time in which I faced the issue but with not success. Nice to know that now this option is enabled!

**Comment by danielesalvatore** [comment]
I will close the issue based on the your comment @jeznag
