### ISSUE TITLE
Request to fix build failure ...

### ISSUE THREAD

**Issue by ClaudiuOctavianMuresan** [pkgcloud/pkgcloud#641]
Hi,

 Is it possible to fix the latest build jshint errors?

```
./node_modules/.bin/jshint --exclude-path .gitignore .
lib/pkgcloud/amazon/storage/client/containers.js: line 131, col 12, 'deleteFiles' was used before it was defined.
lib/pkgcloud/amazon/storage/client/containers.js: line 135, col 12, 'destroyFile' was used before it was defined.

lib/pkgcloud/google/storage/client/containers.js: line 112, col 12, 'deleteFiles' was used before it was defined.
lib/pkgcloud/google/storage/client/containers.js: line 116, col 12, 'destroyFile' was used before it was defined.

lib/pkgcloud/openstack/context/identity.js: line 195, col 12, 'getTenantId' was used before it was defined.

lib/pkgcloud/openstack/context/service.js: line 114, col 12, 'getUrl' was used before it was defined.
lib/pkgcloud/openstack/context/service.js: line 131, col 12, 'endpointMatchDesiredInterface' was used before it was defined.

lib/pkgcloud/openstack/database/client/users.js: line 146, col 12, 'makeRequest' was used before it was defined.

test/common/base/client-test.js: line 41, col 16, 'handleResponse' was used before it was defined.
test/common/base/client-test.js: line 84, col 16, 'handleResponse' was used before it was defined.

test/common/databases/flavor-test.js: line 126, col 12, 'setupGetFlavorsMock' was used before it was defined.

11 errors
```

  We would like to have this new version available as soon as possible as it addresses various security vulnerabilities fixes. 
  If this is not possible in the next few days please let me know how can I contribute to get it done.
  Also, what would be the effort of dropping gcloud dependency (deprecated) to move to @google-cloud/storage?
 
Regards,
 Claudiu

**Comment by Clement134** [comment]
It sould be fixed with #642

**Comment by ClaudiuOctavianMuresan** [comment]
Thank you so much. Do you have a date for when the new version will get published to npm?

**Comment by Clement134** [comment]
I don't really know when this new version will be published on npm.  In fact, I don't even know who can publish a new version to npm.

**Comment by mattgrande** [comment]
Yess, sorry for the delay. @rosskukulinski - I think we're good to go.

**Comment by rosskukulinski** [comment]
@mattgrande do you want 1.4.1 or 1.5.0?

**Comment by rosskukulinski** [comment]
npm notice === Tarball Details === 
npm notice name:          pkgcloud                                
npm notice version:       1.6.0                                   
npm notice package size:  194.1 kB                                
npm notice unpacked size: 947.3 kB                                
npm notice shasum:        9a81717e6e1ff8683624b72c9b34a08580663be4
npm notice integrity:     sha512-342NDJLNRQBck[...]749wyTITzgRdw==
npm notice total files:   360
