### ISSUE TITLE
Update Keystone API version  to 3

### ISSUE THREAD

**Issue by volchonok27** [pkgcloud/pkgcloud#684]
Update api version to 3. Change Authentication Method.
They are discontinuing v2 of the Keystone API on 24th March 2020. All users of the Keystone API must now use version 3, and make the changes required to do so.
https://storage.p19.cloud.ovh.net/v1/AUTH_47f7eb0153a7447799377451f59357ce/public/keystone-v3-request.txt
#683 
@jcrugzz

**Comment by nickngsr** [comment]
Keystone v3 is already supported (tested with OVH) use the following client config:

pkgcloud.storage.createClient({
    provider: 'openstack',
    username: ***,
    password: ***,
    region: ***,
    authUrl: 'https://auth.cloud.ovh.net',
    keystoneAuthVersion: 'v3',
    domainId: 'default',
    domainName: 'default'
});

**Comment by volchonok27** [comment]
> Keystone v3 is already supported (tested with OVH) use the following client config:
> 
> pkgcloud.storage.createClient({
> provider: 'openstack',
> username: ***,
> password: ***,
> region: ***,
> authUrl: 'https://auth.cloud.ovh.net',
> keystoneAuthVersion: 'v3',
> domainId: 'default',
> domainName: 'default'
> });
